    spring:
        data:
            cassandra:
                keyspace-name: main
                username: EsEzOQywyoNSKiWkOfqebDYl
                password: O210x,GZqjf1EWobOvuUaeupFmm8gjZ647pSzT2,uZlOqhe7lZXeDJ4z+6raDcMtYvJI+9dbDS+wIiAv6ZAxN36r-1dON,,Ozwdt2TKXh3mN0+M_kZG2q+u1ikLpO7hQ 
                schema-action: create-if-not-exists
                request:
                    timeout: 10s
                connection:
                    connect-timeout: 10s
                    init-query-timeout: 10s
        

        mail:
            host: smtp.gmail.com
            username: testnumber1024@gmail.com   
            password: apzqzusewvkvjrdj
            port: 587

            properties:
                mail:
                    smtp:
                        auth: true
                        starttls:
                            enable: true
     
    datastax.astra:
        secure-connect-bundle: secure-connect.zip
     
    astra.db:
        id: a34437fe-c095-4ccb-8364-9a4a8fbd1e24-1
        region: asia-south1
        keyspace: main
        application.token: AstraCS:EsEzOQywyoNSKiWkOfqebDYl:20e016f619af120f7f105cf4a8a46fccbc2d3c436c42b97b449ca0df1f99a643 
     
  